export const DubaiEmirates = [
  {
    name: 'Abu Dhabi',
    cities: [
      'Abu Dhabi ',
      'Abu al Abyad',
      'Al Ain',
      'Al Ajban',
      'Al Aryam',
      'Al Faqa',
      'Al Mirfa',
      'Al Shuwaib',
      'Al Yahar',
      'Dalma',
      'Ghayathi',
      'Habshan',
      'Liwa Oasis',
      'Madinat Zayed',
      'Marawah',
      'Nahil',
      'Ruwais',
      'Sila',
      'Sweihan',
    ],
  },
  {
    name: 'Dubai',
    cities: [
      'Al Awir',
      'Al Faqa',
      'Al Khawaneej',
      'Al Lisaili',
      'Al Ruwayyah',
      'Dubai ',
      'Hatta',
      'Jebel Ali',
      'Lahbab',
    ],
  },
  {
    name: 'Sharjah',
    cities: [
      'Al Madam',
      'Al Hamriyah',
      'Al Bithnah',
      'Dibba Al-Hisn',
      'Dhaid',
      'Khor Fakkan ',
      'Kalba',
      'Mleiha',
      'Sharjah',
      'Zubarah',
    ],
  },
  {
    name: 'Ajman',
    cities: ['Ajman', 'Al Manama', 'Masfut'],
  },
  {
    name: 'Umm Al Quwain',
    cities: [
      'Falaj Al Mualla',
      'Al Rashidya',
      'Al Rafaah',
      'Al Salamah',
      'Umm Al Quwain',
    ],
  },
  {
    name: 'Ras Al Khaimah',
    cities: [
      'Ras Al Khaimah',
      'Al Jazirah Al Hamra',
      'Adhen',
      'Al Hamraniyah',
      'Al Jeer',
      'Al Qusaidat',
      'Al Qor',
      'Asimah',
      'Digdaga',
      'Ghalilah',
      'Ghayl',
      'Huwaylat',
      'Khatt',
      'Khor Khwair',
      'Masafi',
      'Shaam',
      'Wadi Shah',
    ],
  },
  {
    name: 'Fujairah',
    cities: [
      'Al Halah',
      'Al Bithnah',
      'Al Badiyah',
      'Dibba Al-Fujairah',
      'Dadna',
      'Fujairah',
      'Ghub',
      'Mirbah',
      'Qidfa',
    ],
  },
];
export const DubaiCities = [
  'Abu Dhabi ',
  'Abu al Abyad',
  'Al Ain',
  'Al Ajban',
  'Al Aryam',
  'Al Faqa',
  'Al Mirfa',
  'Al Shuwaib',
  'Al Yahar',
  'Dalma',
  'Ghayathi',
  'Habshan',
  'Liwa Oasis',
  'Madinat Zayed',
  'Marawah',
  'Nahil',
  'Ruwais',
  'Sila',
  'Sweihan',

  'Al Awir',
  'Al Faqa',
  'Al Khawaneej',
  'Al Lisaili',
  'Al Ruwayyah',
  'Dubai ',
  'Hatta',
  'Jebel Ali',
  'Lahbab',

  'Al Madam',
  'Al Hamriyah',
  'Al Bithnah',
  'Dibba Al-Hisn',
  'Dhaid',
  'Khor Fakkan ',
  'Kalba',
  'Mleiha',
  'Sharjah',
  'Zubarah',
  'Ajman',
  'Al Manama',
  'Masfut',

  'Falaj Al Mualla',
  'Al Rashidya',
  'Al Rafaah',
  'Al Salamah',
  'Umm Al Quwain',
  'Ras Al Khaimah',
  'Al Jazirah Al Hamra',
  'Adhen',
  'Al Hamraniyah',
  'Al Jeer',
  'Al Qusaidat',
  'Al Qor',
  'Asimah',
  'Digdaga',
  'Ghalilah',
  'Ghayl',
  'Huwaylat',
  'Khatt',
  'Khor Khwair',
  'Masafi',
  'Shaam',
  'Wadi Shah',
  'Al Halah',
  'Al Bithnah',
  'Al Badiyah',
  'Dibba Al-Fujairah',
  'Dadna',
  'Fujairah',
  'Ghub',
  'Mirbah',
  'Qidfa',
];
