import { LocationKind } from '../models/location-types.model';

export class LocationCategory {
  public static locationCategories: LocationKind[] = [
    {
      name: 'Residential',
      imgSrc: 'assets/images/icon-1.png',
      id: 1,
      checked: false,
    },
    {
      name: 'Commercial',
      imgSrc: 'assets/images/icon-2.png',
      id: 2,
      checked: false,
    },
    {
      name: 'Studio',
      imgSrc: 'assets/images/icon-3.png',
      id: 3,
      checked: false,
    },
    {
      name: 'Transportation',
      imgSrc: 'assets/images/icon-4.png',
      id: 4,
      checked: false,
    },
  ];

  public static professionalLocations = [
    {
      title: '',
      linkText: '',
      link: '/',
      imageUrl: 'assets/images/dummy/default_image.png',
      position: 0,
      tileId: 0,
      id: 0,
      header: '',
      subHeader: '',
      type: '',
      description: '',
    },
    {
      title: '',
      linkText: '',
      link: '/',
      imageUrl: 'assets/images/dummy/default_image.png',
      position: 0,
      tileId: 0,
      id: 0,
      header: '',
      subHeader: '',
      type: '',
      description: '',
    },
  ];

  public static header = 'Location Genie for Professionals';
  public static subHeader =
    'We can help you find off-market locations, pull permits and negotiate the best rates, at no cost';

  public static dummyLocation = {
    title: '',
    linkText: '',
    link: '/',
    imageUrl: 'assets/images/dummy/default_image.png',
    position: 0,
    id: 0,
    tileId: 0,
    type: '',
    header: '',
    subHeader: '',
    description: '',
  };

  public static dummyLocations = [
    {
      title: '',
      linkText: '',
      link: '/',
      imageUrl: 'assets/images/dummy/default_image.png',
      position: 0,
      id: 0,
      tileId: 0,
      type: '',
      header: '',
      subHeader: '',
      description: '',
    },
    {
      title: '',
      linkText: '',
      link: '/',
      imageUrl: 'assets/images/dummy/default_image.png',
      position: 0,
      id: 0,
      tileId: 0,
      type: '',
      header: '',
      subHeader: '',
      description: '',
    },
    {
      title: '',
      linkText: '',
      link: '/',
      imageUrl: 'assets/images/dummy/default_image.png',
      position: 0,
      id: 0,
      tileId: 0,
      type: '',
      header: '',
      subHeader: '',
      description: '',
    },
    {
      title: '',
      linkText: '',
      link: '/',
      imageUrl: 'assets/images/dummy/default_image.png',
      position: 0,
      id: 0,
      tileId: 0,
      type: '',
      header: '',
      subHeader: '',
      description: '',
    },
    {
      title: '',
      linkText: '',
      link: '/',
      imageUrl: 'assets/images/dummy/default_image.png',
      position: 0,
      id: 0,
      tileId: 0,
      type: '',
      header: '',
      subHeader: '',
      description: '',
    },
    {
      title: '',
      linkText: '',
      link: '/',
      imageUrl: 'assets/images/dummy/default_image.png',
      position: 0,
      id: 0,
      tileId: 0,
      type: '',
      header: '',
      subHeader: '',
      description: '',
    },
    {
      title: '',
      linkText: '',
      link: '/',
      imageUrl: 'assets/images/dummy/default_image.png',
      position: 0,
      id: 0,
      tileId: 0,
      type: '',
      header: '',
      subHeader: '',
      description: '',
    },
    {
      title: '',
      linkText: '',
      link: '/',
      imageUrl: 'assets/images/dummy/default_image.png',
      position: 0,
      id: 0,
      tileId: 0,
      type: '',
      header: '',
      subHeader: '',
      description: '',
    },
    {
      title: '',
      linkText: '',
      link: '/',
      imageUrl: 'assets/images/dummy/default_image.png',
      position: 0,
      id: 0,
      tileId: 0,
      type: '',
      header: '',
      subHeader: '',
      description: '',
    },
    {
      title: '',
      linkText: '',
      link: '/',
      imageUrl: 'assets/images/dummy/default_image.png',
      position: 0,
      id: 0,
      tileId: 0,
      type: '',
      header: '',
      subHeader: '',
      description: '',
    },
  ];
}
